# Generated by Django 4.1.3 on 2023-03-14 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_userinfo_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
