# Generated by Django 4.1.3 on 2023-03-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_last_edit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_follows_me',
        ),
    ]
