# Generated by Django 4.1.3 on 2023-05-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_userinfo_user_follows_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='network/static/network/cat_twitter.png', upload_to='network/static/network/uploads/'),
        ),
    ]
