# Generated by Django 4.1.3 on 2023-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/network/cat_twitter.png', upload_to='network/'),
        ),
    ]
